### ISSUE TITLE
Issue with plugin "similarity" when running scheduled Github action

### ISSUE THREAD

**Issue by JesperDramsch** [getnikola/nikola-action#3]
First, thanks for all the amazing work with Nikola. 

I hope this issue is correct in this repo because it only happens with the Github Action. However, it pertains to the `similarity` plugin too.

I've recently started using scheduled Github Actions to publish scheduled blog posts automatically. First, I had also committed the `output` folder to `src`, but because some other behaviour was weird (files change because of changing UUID on `code-block` builds), I went back to the guide and updated the `.gitignore` to include the `doit.db` and the `output` folder. Now there's some peculiar behaviour.

When I push the src, it builds fine. When I trigger the workflow manually with `workflow_dispatch`, it's fine. But on the scheduled action, there is an error with the similarity plugin. Maybe it's important that the post the error happens on is also a scheduled post?

Here's the build output, when it works, starting at line number 467:

```.  similarity:output/posts/a-life-of-convergence-and-divergence/index.html.related.json
[2021-05-01 22:27:51] INFO: gensim.corpora.dictionary: adding document #0 to Dictionary(0 unique tokens: [])
[2021-05-01 22:27:51] INFO: gensim.corpora.dictionary: built Dictionary(2773 unique tokens: ['absolute', 'act', 'additional', 'adjusting', 'advance']...) from 11 documents (total 6350 corpus positions)
[2021-05-01 22:27:51] INFO: gensim.utils: Dictionary lifecycle event {'msg': "built Dictionary(2773 unique tokens: ['absolute', 'act', 'additional', 'adjusting', 'advance']...) from 11 documents (total 6350 corpus positions)", 'datetime': '2021-05-01T22:27:51.913396', 'gensim': '4.0.1', 'python': '3.8.9 (default, Apr 10 2021, 15:47:22) \n[GCC 8.3.0]', 'platform': 'Linux-5.4.0-1046-azure-x86_64-with-glibc2.2.5', 'event': 'created'}
[2021-05-01 22:27:51] INFO: gensim.models.lsimodel: using serial LSI version on this node
[2021-05-01 22:27:51] INFO: gensim.models.lsimodel: updating model with new documents
[2021-05-01 22:27:51] INFO: gensim.models.lsimodel: preparing a new chunk of documents
[2021-05-01 22:27:51] INFO: gensim.models.lsimodel: using 100 extra samples and 2 power iterations
[2021-05-01 22:27:51] INFO: gensim.models.lsimodel: 1st phase: constructing (2773, 102) action matrix
[2021-05-01 22:27:51] INFO: gensim.models.lsimodel: orthonormalizing (2773, 102) action matrix
[2021-05-01 22:27:51] INFO: gensim.models.lsimodel: 2nd phase: running dense svd on (102, 11) matrix
[2021-05-01 22:27:51] INFO: gensim.models.lsimodel: computing the final decomposition
[2021-05-01 22:27:51] INFO: gensim.models.lsimodel: keeping 2 factors (discarding 11.642% of energy spectrum)
[2021-05-01 22:27:51] INFO: gensim.models.lsimodel: processed documents up to #11
[2021-05-01 22:27:51] INFO: gensim.models.lsimodel: topic #0(211.700): 0.623*"=" + 0.278*"data" + 0.247*"seismic" + 0.207*"neural" + 0.170*"jesper" + 0.154*"learning" + 0.137*"training" + 0.132*"sören" + 0.128*"deep" + 0.126*"machine"
[2021-05-01 22:27:51] INFO: gensim.models.lsimodel: topic #1(50.981): 0.250*"science" + 0.206*"2019" + 0.189*"can" + 0.186*"2018" + 0.181*"machine" + 0.179*"python" + 0.171*"learning" + -0.156*"=" + 0.153*"2020" + 0.150*"thesis"
[2021-05-01 22:27:51] INFO: gensim.utils: LsiModel lifecycle event {'msg': 'trained LsiModel(num_terms=2773, num_topics=2, decay=1.0, chunksize=20000) in 0.07s', 'datetime': '2021-05-01T22:27:51.986212', 'gensim': '4.0.1', 'python': '3.8.9 (default, Apr 10 2021, 15:47:22) \n[GCC 8.3.0]', 'platform': 'Linux-5.4.0-1046-azure-x86_64-with-glibc2.2.5', 'event': 'created'}
[2021-05-01 22:27:51] WARNING: gensim.similarities.docsim: scanning corpus to determine the number of features (consider setting `num_features` explicitly)
[2021-05-01 22:27:51] INFO: gensim.similarities.docsim: creating matrix with 11 documents and 2 features
```

And here's the output when it repeatedly failed, starting at line 319:

``` .  similarity:output/posts/a-life-of-convergence-and-divergence/index.html.related.json
[2021-05-02 03:57:51] INFO: Nikola: posts/a-life-of-convergence-and-divergence.rst is scheduled to be published in the future (2021-05-04 11:33:00+01:00)
[2021-05-02 03:57:52] INFO: gensim.corpora.dictionary: adding document #0 to Dictionary(0 unique tokens: [])
[2021-05-02 03:57:52] INFO: gensim.corpora.dictionary: built Dictionary(2773 unique tokens: ['absolute', 'act', 'additional', 'adjusting', 'advance']...) from 11 documents (total 6350 corpus positions)
[2021-05-02 03:57:52] INFO: gensim.utils: Dictionary lifecycle event {'msg': "built Dictionary(2773 unique tokens: ['absolute', 'act', 'additional', 'adjusting', 'advance']...) from 11 documents (total 6350 corpus positions)", 'datetime': '2021-05-02T03:57:52.522992', 'gensim': '4.0.1', 'python': '3.8.9 (default, Apr 10 2021, 15:47:22) \n[GCC 8.3.0]', 'platform': 'Linux-5.4.0-1046-azure-x86_64-with-glibc2.2.5', 'event': 'created'}
[2021-05-02 03:57:52] INFO: gensim.models.lsimodel: using serial LSI version on this node
[2021-05-02 03:57:52] INFO: gensim.models.lsimodel: updating model with new documents
[2021-05-02 03:57:52] INFO: gensim.models.lsimodel: preparing a new chunk of documents
[2021-05-02 03:57:52] INFO: gensim.models.lsimodel: using 100 extra samples and 2 power iterations
[2021-05-02 03:57:52] INFO: gensim.models.lsimodel: 1st phase: constructing (2773, 102) action matrix
[2021-05-02 03:57:52] INFO: gensim.models.lsimodel: orthonormalizing (2773, 102) action matrix
[2021-05-02 03:57:52] INFO: gensim.models.lsimodel: 2nd phase: running dense svd on (102, 11) matrix
[2021-05-02 03:57:52] INFO: gensim.models.lsimodel: computing the final decomposition
[2021-05-02 03:57:52] INFO: gensim.models.lsimodel: keeping 2 factors (discarding 11.642% of energy spectrum)
[2021-05-02 03:57:52] INFO: gensim.models.lsimodel: processed documents up to #11
[2021-05-02 03:57:52] INFO: gensim.models.lsimodel: topic #0(211.700): 0.623*"=" + 0.278*"data" + 0.247*"seismic" + 0.207*"neural" + 0.170*"jesper" + 0.154*"learning" + 0.137*"training" + 0.132*"sören" + 0.128*"deep" + 0.126*"machine"
[2021-05-02 03:57:52] INFO: gensim.models.lsimodel: topic #1(50.981): -0.250*"science" + -0.206*"2019" + -0.189*"can" + -0.186*"2018" + -0.181*"machine" + -0.179*"python" + -0.171*"learning" + 0.156*"=" + -0.153*"2020" + -0.150*"thesis"
[2021-05-02 03:57:52] INFO: gensim.utils: LsiModel lifecycle event {'msg': 'trained LsiModel(num_terms=2773, num_topics=2, decay=1.0, chunksize=20000) in 0.05s', 'datetime': '2021-05-02T03:57:52.584552', 'gensim': '4.0.1', 'python': '3.8.9 (default, Apr 10 2021, 15:47:22) \n[GCC 8.3.0]', 'platform': 'Linux-5.4.0-1046-azure-x86_64-with-glibc2.2.5', 'event': 'created'}
[2021-05-02 03:57:52] WARNING: gensim.similarities.docsim: scanning corpus to determine the number of features (consider setting `num_features` explicitly)
[2021-05-02 03:57:52] INFO: gensim.similarities.docsim: creating matrix with 11 documents and 2 features
TaskError - taskid:similarity:output/posts/a-life-of-convergence-and-divergence/index.html.related.json
PythonAction Error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/doit/action.py", line 437, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "/github/workspace/plugins/similarity/similarity.py", line 124, in write_similar
    with open(path, 'w+') as outf:
FileNotFoundError: [Errno 2] No such file or directory: 'output/posts/a-life-of-convergence-and-divergence/index.html.related.json'

########################################
similarity:output/posts/a-life-of-convergence-and-divergence/index.html.related.json <stdout>: 
```

I don't know if it matters, but the file `posts/a-life-of-convergence-and-divergence/index.html.related.json` exists in the branch used to publish the website.

**Comment by Kwpolska** [comment]
This seems related: 

    [2021-05-02 03:57:51] INFO: Nikola: posts/a-life-of-convergence-and-divergence.rst is scheduled to be published in the future (2021-05-04 11:33:00+01:00)

My guess would be that the plugin is not handling future posts correctly and trying to generate output files for them. Could you try patching the plugin to check the publication status and avoid creating the file if it’s not yet published?

**Comment by JesperDramsch** [comment]
Hey thanks for having me take a deeper look into the code. On the one hand, yes, the plugin does not consider scheduled posts. However, I think the actual problem is that the plugin _should_ be a LateTask, as it expects all posts to be rendered at execution. I'll test it live and then if successful send a PR.
